import "./globals.css";
export const metadata = {
  title: "Learning Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-blue-500 p-10">
          <p>Header</p>
        </header>
        
        {children}

        <footer className="bg-gray-200 p-10">
          <p>Footer</p>
        </footer>
        
      </body>
    </html>
  );
}
